unpackaged/main/default/objects/Child_Form__c/Child_Form__c.object-meta.xml
<CustomObject>
    <label>Child Form</label>
    <nameField>
        <displayFormat>OFF-{0000}</displayFormat>
        <label>Child Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Child Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Child_Form__c/fields/Is_Required__c.field-meta.xml
<CustomField>
        <fullName>Is_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Required?</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/Child_Form__c/fields/Label__c.field-meta.xml
<CustomField>
        <fullName>Label__c</fullName>
        <label>Label</label>
        <length>255</length>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/objects/Child_Form__c/fields/Object_Name__c.field-meta.xml
<CustomField>
        <fullName>Object_Name__c</fullName>
        <label>Object Name</label>
        <length>20</length>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/objects/Child_Form__c/fields/Sub_Type__c.field-meta.xml
<CustomField>
        <fullName>Sub_Type__c</fullName>
        <label>Sub Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Check box</fullName>
                </value>
                <value>
                    <fullName>Radio button</fullName>
                </value>
                <value>
                    <fullName>Drop down</fullName>
                </value>
                <value>
                    <fullName>First Name</fullName>
                </value>
                <value>
                    <fullName>Last Name</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Child_Form__c/fields/Type__c.field-meta.xml
<CustomField>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Section header</fullName>
                </value>
                <value>
                    <fullName>Linked fields</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Child_Form__c/fields/Values__c.field-meta.xml
<CustomField>
        <fullName>Values__c</fullName>
        <description>Auto populated values
Drop down values</description>
        <label>Values</label>
        <type>TextArea</type>
    </CustomField>

unpackaged/main/default/classes/DataTableEditRemoveController.cls
public class DataTableEditRemoveController {

   public List<Account> accs { get; set; }
  public List<Child_Form__c> childForm{get;set;}
   //used to get a hold of the account record selected for deletion
   public string SelectedAccountId { get; set; }
  
   public DataTableEditRemoveController() {
       //load account data into our DataTable
       LoadData();
   }
   
   
  
  
   private void LoadData() {
   
   String FormId = 'a0028000003dswV';
        childForm =  [select Is_Required__c,Label__c,Object_Name__c,Sub_Type__c,Type__c,Values__c 
        from Child_Form__c  limit :3];
   
       accs = [Select id, name, BillingStreet, BillingCity, BillingPostalCode, BillingCountry from Account limit 20];
   }
  
   public void DeleteAccount()
   {
      // if for any reason we are missing the reference 
      if (SelectedAccountId == null) {
      
         return;
      }
     
      // find the account record within the collection
      Child_Form__c tobeDeleted = null;
      for(Child_Form__c a : childForm)
       if (a.Id == SelectedAccountId) {
          tobeDeleted = a;
          break;
       }
      
      //if account record found delete it
      if (tobeDeleted != null) {
       Delete tobeDeleted;
      }
     
      //refresh the data
      LoadData();
   }    
  
  
}