unpackaged/main/default/objects/Child_Form__c/Child_Form__c.object-meta.xml
<CustomObject>
    <label>Child Form</label>
    <nameField>
        <displayFormat>OFF-{0000}</displayFormat>
        <label>Child Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Child Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Child_Form__c/fields/Field_Name__c.field-meta.xml
<CustomField>
        <fullName>Field_Name__c</fullName>
        <label>Field Name</label>
        <length>50</length>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/objects/Child_Form__c/fields/Form_Parent__c.field-meta.xml
<CustomField>
        <fullName>Form_Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Form Parent</label>
        <referenceTo>Form_Parent__c</referenceTo>
        <relationshipLabel>Child Forms</relationshipLabel>
        <relationshipName>Child_Forms</relationshipName>
        <type>Lookup</type>
    </CustomField>

unpackaged/main/default/objects/Child_Form__c/fields/Is_Required__c.field-meta.xml
<CustomField>
        <fullName>Is_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Required?</label>
        <type>Checkbox</type>
    </CustomField>

unpackaged/main/default/objects/Child_Form__c/fields/Label__c.field-meta.xml
<CustomField>
        <fullName>Label__c</fullName>
        <label>Label</label>
        <length>255</length>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/objects/Child_Form__c/fields/Object_Name__c.field-meta.xml
<CustomField>
        <fullName>Object_Name__c</fullName>
        <label>Object Name</label>
        <length>20</length>
        <type>Text</type>
    </CustomField>

unpackaged/main/default/objects/Child_Form__c/fields/Sub_Type__c.field-meta.xml
<CustomField>
        <fullName>Sub_Type__c</fullName>
        <label>Sub Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Check box</fullName>
                </value>
                <value>
                    <fullName>Radio button</fullName>
                </value>
                <value>
                    <fullName>Drop down</fullName>
                </value>
                <value>
                    <fullName>First Name</fullName>
                </value>
                <value>
                    <fullName>Last Name</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Child_Form__c/fields/Type__c.field-meta.xml
<CustomField>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Section header</fullName>
                </value>
                <value>
                    <fullName>Linked fields</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

unpackaged/main/default/objects/Child_Form__c/fields/Values__c.field-meta.xml
<CustomField>
        <fullName>Values__c</fullName>
        <description>Auto populated values
Drop down values</description>
        <label>Values</label>
        <type>TextArea</type>
    </CustomField>

unpackaged/main/default/objects/Form_Parent__c/Form_Parent__c.object-meta.xml
<CustomObject>
    <label>Form Parent</label>
    <nameField>
        <label>Form Parent Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Parents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/dynamicForm.cls
public with sharing class dynamicForm {

 
public List<Child_Form__c> childFormList{get;set;}

public List<Childclass> childList{get;set;}

public dynamicForm() 
{
        String FormId = 'a0028000003dswV';
        childFormList =  [select id,Name,Field_Name__c,Form_Parent__c,Is_Required__c,Label__c,Object_Name__c,Sub_Type__c,Type__c,Values__c 
        from Child_Form__c where  Form_Parent__c = :FormId];
        childList = new List<Childclass>();
         Childclass childClssObj ;
         for(Child_Form__c childObj :  childFormList)
         {
             childClssObj =  new Childclass(childObj.Field_Name__c,''+childObj.Form_Parent__c,childObj.Is_Required__c,childObj.Label__c,childObj.Object_Name__c,childObj.Sub_Type__c,childObj.Type__c,childObj.Values__c);
             childList.add(childClssObj);           
         }
       System.debug('childList....'+childList); 
}

public static List<SelectOption> getItemsvalues(String values)
    {
         List<SelectOption> options = new List<SelectOption>();
        for(String key : values.split(','))
        {
            options.add(new SelectOption(key,key));
        }   
        return options;
    }
    
public void Save(){}    
public class Childclass { 

public String FieldName{get;set;}
public String parent{get;set;}
public boolean isRequired{get;set;}
public String Label{get;set;}
public String ObjectName{get;set;}
public String SubType{get;set;}
public String Type{get;set;}
public String value{get;set;}
public String dropDownSelectValue{get;set;}
public String sectionHeaderValue{get;set;}
public List<SelectOption> dropDownValues{get;set;}
     
    public Childclass(String FieldName , String parent ,boolean isRequired ,String Label,String ObjectName ,String SubType ,String Type , String value)
    {
        this.FieldName = FieldName;
        this.parent = parent;
        
        if(isRequired == null)
        this.isRequired =  false;
        else
        this.isRequired = isRequired;
        
        this.Label = Label;
        this.ObjectName = ObjectName;
        this.SubType = SubType;
        this.Type = Type;
        
        this.Type = Type;
        if(Type == 'Section header'){
        	sectionHeaderValue = value;
        }
        else
        {
        	this.dropDownValues = dynamicForm.getItemsvalues(value);	
        }
        
        
    }
}
}